# Use postgres/example user/password credentials
version: '3.1'

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: justclick
            POSTGRES_PASSWORD: justclick
            POSTGRES_DB: justclick
        ports:
            - 5432:5432
        networks:
            - default

    adminer:
        image: adminer
        restart: always
        ports:
            - 8085:8080
        networks:
            - default
        depends_on:
            - db

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        environment:
            - node.name=es
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esData:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - default

volumes:
  esData:
    driver: local

networks:
    default:
        driver: bridge